export default Object.freeze({
  ACCOUNT: "Account",
  ACCOUNT_DETAILS: "AccountDetails",
  ADMIN_LISTING_ADD: "AdminAdder",
  ADMIN_LISTING_EDIT: "AdminEdit",
  ADMIN_LISTING_UPDATE: "AdminUpdate",
  CART: "Cart",
  CHECKOUT: "Checkout",
  MENU: "Menu",
  LISTING: "Listing",
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  WELCOME: "Welcome",
  OTP: "OTP",
  PAYMENT: "Payment",
});
