export default Object.freeze({
  ACCOUNT: "Account",
  ACCOUNT_DETAILS: "AccountDetails",
  CART: "Cart",
  CHECKOUT: "Checkout",
  MENU: "Menu",
  LISTING: "Listing",
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  WELCOME: "Welcome",
  ORDER_HISTORY: "OrederHistory",
  OTP: "OTP",
  PAYMENT: "Payment",
  ORDER_SUMMARY: "Summary",
  APP_NAV: "App_Nav",
  ONLINE_ACCOUNT: "Online_Account",
  FORGET_PASSWORD: "Forget_Password",
  CHANGE_PASSWORD: "Change_Password",
});
