export default Object.freeze({
  ACCOUNT: "Account",
  ADMIN_LISTING_ADD: "AdminAdder",
  ADMIN_LISTING_EDIT: "AdminEdit",
  ADMIN_LISTING_UPDATE: "AdminUpdate",
  CART: "Cart",
  LISTINGS: "Listings",
  LISTING: "Listing",
  LISTING_DETAILS: "ListingDetails",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  WELCOME: "Welcome",
});
